import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const packageJson = JSON.parse(await readFile(resolve(appDir, "package.json"), "utf8"));
const version = packageJson.version;

if (typeof version !== "string" || version.length === 0) {
  throw new Error("Missing package.json version");
}

const generated = `// Generated by scripts/write-version.mjs. Do not edit by hand.
export const appVersion = ${JSON.stringify(version)};
export const appBuild = ${JSON.stringify(`${version}-beta`)};
`;

await mkdir(resolve(appDir, "src"), { recursive: true });
await writeFile(resolve(appDir, "src/version.ts"), generated);
console.log(`[eutherbooks-player-version] ${version}`);
